name: brian_cuda
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=h1aa0949_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py310h139afa4_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pyzmq=27.1.0=py310h4f33d48_0
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_ha0e22de_103
  - tornado=6.5.2=py310h7c4b9e2_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - brian2==2.8.0
      - brian2cuda==1.0a7
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==3.2.1
      - fonttools==4.61.1
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - numpy==2.2.6
      - pandas==2.3.3
      - pillow==12.0.0
      - pyarrow==22.0.0
      - pyparsing==3.3.0a1
      - pytz==2025.2
      - seaborn==0.13.2
      - sympy==1.14.0
      - tzdata==2025.2
prefix: /root/anaconda3/envs/brain
